#
#Vagrantfile for the quickstart tutorial
# Script configuration:
#
# Arista vEOS box.
# Please change this to match your installed version
# (use `vagrant box list` to see what you have installed).

VEOS_BOX = "NXOS-box"
Vagrant.configure(2) do |config|

    config.ssh.shell = "zsh"
    config.ssh.username = "root"
    config.ssh.password = "tessel2" 

    config.vm.define "base" do |base|
        # This box will be downloaded and added automatically if you don't
        # have it already.
        base.vm.box = "hashicorp/bionic64"
        base.vm.network :forwarded_port, guest: 22, host: 12200, id: 'ssh'
        base.vm.network "private_network", virtualbox__intnet: "link_1", ip: "10.0.1.100"
        base.vm.network "private_network", virtualbox__intnet: "link_2", ip: "10.0.2.100"
        base.vm.provision "shell", inline: "apt-get update; apt-get install lldpd -y"
    end

    config.vm.define "eos" do |eos|
        eos.vm.box = VEOS_BOX
        eos.vm.network :forwarded_port, guest: 22, host: 12201, id: 'ssh'
        eos.vm.network :forwarded_port, guest: 443, host: 12443, id: 'https'
        eos.vm.network "private_network", virtualbox__intnet: "link_1", ip: "169.254.1.11", auto_config: false
        eos.vm.network "private_network", virtualbox__intnet: "link_2", ip: "169.254.1.11", auto_config: false
    end
end
